name: Java Maven Build and Copilot Summary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Install Copilot
      run: |
        curl -Lo /tmp/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
        sudo install /tmp/copilot /usr/local/bin/copilot
        echo 'export PATH="/usr/local/bin:$PATH"' >> $GITHUB_ENV

    - name: Create PR Summary with Copilot
      run: |
        /usr/local/bin/copilot svc summary --json > summary.json
        
    - name: Add Copilot Summary to PR Description
      run: |
        summary=$(jq -r '.summary' summary.json)
        echo "## Copilot Summary\n\n${summary}" >> $GITHUB_EVENT_PATH

